---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  pre_tasks:
    - name: APT update cache
      apt:
        update-cache: true
      failed_when: false
      changed_when: false

  roles:
    - role: bertvv.samba
      tags:
        - samba

  tasks:
    - import_tasks: tasks/default.yml
      tags: default

    - import_tasks: tasks/docker.yml
      tags: docker

    - import_tasks: tasks/traefik.yml
      tags: traefik

    - import_tasks: tasks/portainer.yml
      tags: portainer

    - import_tasks: tasks/heimdall.yml
      tags: heimdall

    - import_tasks: tasks/glances.yml
      tags: glances

    - import_tasks: tasks/nextcloud.yml
      tags: nextcloud

    - import_tasks: tasks/plex.yml
      tags: plex

    - import_tasks: tasks/jellyfin.yml
      tags: jellyfin
      