---
- name: APT install required packages
  apt:
    name: 
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - software-properties-common 
      - python3-pip 
    state: present
  register: result
  until: result is succeeded
