---
- name: APT update cache
  apt:
    update_cache: yes
    # cache_valid_time: 3600
  register: result
  until: result is succeeded

- name: APT install required packages
  apt:
    name: 
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - software-properties-common 
      - python3-pip 
    state: present
  register: result
  until: result is succeeded
