---
- name: Docker container glances
  docker_container:
    name: glances
    image: "{{ glances_docker_image }}"
    pull: true
    ports:
      - "{{ glances_port_one }}:61208"
      - "{{ glances_port_two }}:61209"
    volumes:
      #- "/glances.conf:/glances/conf/glances.conf"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/timezone:/etc/timezone:ro"
    pid_mode: host
    network_mode: host
    env:
      GLANCES_OPT: "-w"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "glances"
      traefik.frontend.rule: "Host:glances.{{ traefik_acme_domain }}"
      traefik.enable: "{{ glances_available_external }}"
      traefik.port: "61208"