---
- name: Create Heimdall group
  group:
    name: "{{ heimdall_groupname }}"
    gid: "{{ heimdall_gid }}"
    state: present

- name: Create Heimdall user
  user:
    name: "{{ heimdall_username }}"
    uid: "{{ heimdall_uid }}"
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: "{{ heimdall_groupname }}"

- name: Create Heimdall Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ heimdall_username }}"
    group: "{{ heimdall_groupname }}"
  with_items:
    - "{{ heimdall_data_directory }}"

- name: Create Heimdall container
  docker_container:
    name: heimdall
    image: "{{ heimdall_docker_image }}"
    pull: true
    volumes:
      - "{{ heimdall_data_directory }}:/config:rw"
    env:
      PUID: "{{ heimdall_uid }}"
      PGID: "{{ heimdall_gid }}"
      TZ: "{{ timezone }}"
    ports:
      - "{{ heimdall_port_http }}:80"
      - "{{ heimdall_port_https }}:443"
    restart_policy: unless-stopped
    memory: 1g